spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzhhome?allowMultiQueries=true&useSSL=false&characterEncoding=utf-8
    username: wy
    password: Wy19881217
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 443
  ssl:
    key-store: classpath:wangzihan.org.cn.jks
    key-store-password: yale58lc